//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAIFService.MyServicePortServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogonAsUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser {
            get {
                return this.LogonAsUserField;
            }
            set {
                if ((object.ReferenceEquals(this.LogonAsUserField, value) != true)) {
                    this.LogonAsUserField = value;
                    this.RaisePropertyChanged("LogonAsUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag {
            get {
                return this.PropertyBagField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyBagField, value) != true)) {
                    this.PropertyBagField = value;
                    this.RaisePropertyChanged("PropertyBag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyAIFService.MyServicePortServiceReference.ITP_DataContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyAIFService.MyServicePortServiceReference.EntityPostalAddress))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyAIFService.MyServicePortServiceReference.MeterDataInformation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyAIFService.MyServicePortServiceReference.MeterDataRegisterInformation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyAIFService.MyServicePortServiceReference.MeterReadingRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyAIFService.MyServicePortServiceReference.MeterRequests))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyAIFService.MyServicePortServiceReference.FindRequestArgs))]
    public partial class XppObjectBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ITP_DataContract", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyAIFService.MyServicePortServiceReference.EntityPostalAddress))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyAIFService.MyServicePortServiceReference.MeterDataInformation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyAIFService.MyServicePortServiceReference.MeterDataRegisterInformation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyAIFService.MyServicePortServiceReference.MeterReadingRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MyAIFService.MyServicePortServiceReference.MeterRequests))]
    public partial class ITP_DataContract : MyAIFService.MyServicePortServiceReference.XppObjectBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityPostalAddress", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    [System.SerializableAttribute()]
    public partial class EntityPostalAddress : MyAIFService.MyServicePortServiceReference.ITP_DataContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttentionToAddressLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttentionToAddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingComplimentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryRegionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DistrictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyAIFService.MyServicePortServiceReference.NoYes IsPrimaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostBoxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PostalAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ValidFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ValidToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttentionToAddressLine {
            get {
                return this.AttentionToAddressLineField;
            }
            set {
                if ((object.ReferenceEquals(this.AttentionToAddressLineField, value) != true)) {
                    this.AttentionToAddressLineField = value;
                    this.RaisePropertyChanged("AttentionToAddressLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttentionToAddressLine2 {
            get {
                return this.AttentionToAddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AttentionToAddressLine2Field, value) != true)) {
                    this.AttentionToAddressLine2Field = value;
                    this.RaisePropertyChanged("AttentionToAddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingCompliment {
            get {
                return this.BuildingComplimentField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingComplimentField, value) != true)) {
                    this.BuildingComplimentField = value;
                    this.RaisePropertyChanged("BuildingCompliment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryRegionId {
            get {
                return this.CountryRegionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryRegionIdField, value) != true)) {
                    this.CountryRegionIdField = value;
                    this.RaisePropertyChanged("CountryRegionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long District {
            get {
                return this.DistrictField;
            }
            set {
                if ((this.DistrictField.Equals(value) != true)) {
                    this.DistrictField = value;
                    this.RaisePropertyChanged("District");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DistrictName {
            get {
                return this.DistrictNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictNameField, value) != true)) {
                    this.DistrictNameField = value;
                    this.RaisePropertyChanged("DistrictName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyAIFService.MyServicePortServiceReference.NoYes IsPrimary {
            get {
                return this.IsPrimaryField;
            }
            set {
                if ((this.IsPrimaryField.Equals(value) != true)) {
                    this.IsPrimaryField = value;
                    this.RaisePropertyChanged("IsPrimary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Location {
            get {
                return this.LocationField;
            }
            set {
                if ((this.LocationField.Equals(value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostBox {
            get {
                return this.PostBoxField;
            }
            set {
                if ((object.ReferenceEquals(this.PostBoxField, value) != true)) {
                    this.PostBoxField = value;
                    this.RaisePropertyChanged("PostBox");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PostalAddress {
            get {
                return this.PostalAddressField;
            }
            set {
                if ((this.PostalAddressField.Equals(value) != true)) {
                    this.PostalAddressField = value;
                    this.RaisePropertyChanged("PostalAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetNumber {
            get {
                return this.StreetNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetNumberField, value) != true)) {
                    this.StreetNumberField = value;
                    this.RaisePropertyChanged("StreetNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValidFrom {
            get {
                return this.ValidFromField;
            }
            set {
                if ((this.ValidFromField.Equals(value) != true)) {
                    this.ValidFromField = value;
                    this.RaisePropertyChanged("ValidFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValidTo {
            get {
                return this.ValidToField;
            }
            set {
                if ((this.ValidToField.Equals(value) != true)) {
                    this.ValidToField = value;
                    this.RaisePropertyChanged("ValidTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeterDataInformation", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    [System.SerializableAttribute()]
    public partial class MeterDataInformation : MyAIFService.MyServicePortServiceReference.ITP_DataContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyAIFService.MyServicePortServiceReference.MeterDataRegisterInformation[] MeterDataRegisterInformationListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterUnitNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfRegistersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegisterIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyAIFService.MyServicePortServiceReference.MeterDataRegisterInformation[] MeterDataRegisterInformationList {
            get {
                return this.MeterDataRegisterInformationListField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterDataRegisterInformationListField, value) != true)) {
                    this.MeterDataRegisterInformationListField = value;
                    this.RaisePropertyChanged("MeterDataRegisterInformationList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterUnitNumber {
            get {
                return this.MeterUnitNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterUnitNumberField, value) != true)) {
                    this.MeterUnitNumberField = value;
                    this.RaisePropertyChanged("MeterUnitNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfRegisters {
            get {
                return this.NumberOfRegistersField;
            }
            set {
                if ((this.NumberOfRegistersField.Equals(value) != true)) {
                    this.NumberOfRegistersField = value;
                    this.RaisePropertyChanged("NumberOfRegisters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegisterID {
            get {
                return this.RegisterIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RegisterIDField, value) != true)) {
                    this.RegisterIDField = value;
                    this.RaisePropertyChanged("RegisterID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeterDataRegisterInformation", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    [System.SerializableAttribute()]
    public partial class MeterDataRegisterInformation : MyAIFService.MyServicePortServiceReference.ITP_DataContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ConversionFactorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EstimatedAnnualVolumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeasuringUnitIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterRegisterNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyAIFService.MyServicePortServiceReference.IUS_MPO_MeterTimeFrames MeterTimeFrameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MeterTimeFrameDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ConversionFactor {
            get {
                return this.ConversionFactorField;
            }
            set {
                if ((this.ConversionFactorField.Equals(value) != true)) {
                    this.ConversionFactorField = value;
                    this.RaisePropertyChanged("ConversionFactor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EstimatedAnnualVolume {
            get {
                return this.EstimatedAnnualVolumeField;
            }
            set {
                if ((this.EstimatedAnnualVolumeField.Equals(value) != true)) {
                    this.EstimatedAnnualVolumeField = value;
                    this.RaisePropertyChanged("EstimatedAnnualVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeasuringUnitId {
            get {
                return this.MeasuringUnitIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MeasuringUnitIdField, value) != true)) {
                    this.MeasuringUnitIdField = value;
                    this.RaisePropertyChanged("MeasuringUnitId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterRegisterNumber {
            get {
                return this.MeterRegisterNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterRegisterNumberField, value) != true)) {
                    this.MeterRegisterNumberField = value;
                    this.RaisePropertyChanged("MeterRegisterNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyAIFService.MyServicePortServiceReference.IUS_MPO_MeterTimeFrames MeterTimeFrame {
            get {
                return this.MeterTimeFrameField;
            }
            set {
                if ((this.MeterTimeFrameField.Equals(value) != true)) {
                    this.MeterTimeFrameField = value;
                    this.RaisePropertyChanged("MeterTimeFrame");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterTimeFrameDescription {
            get {
                return this.MeterTimeFrameDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterTimeFrameDescriptionField, value) != true)) {
                    this.MeterTimeFrameDescriptionField = value;
                    this.RaisePropertyChanged("MeterTimeFrameDescription");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeterReadingRequest", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    [System.SerializableAttribute()]
    public partial class MeterReadingRequest : MyAIFService.MyServicePortServiceReference.ITP_DataContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustAccountNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MPODeliveryTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MPOEANCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MPOMeteringPointIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyAIFService.MyServicePortServiceReference.MeterDataInformation[] MeterDataInformationListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyAIFService.MyServicePortServiceReference.EntityPostalAddress PostalAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyAIFService.MyServicePortServiceReference.MeterRequests RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyAIFService.MyServicePortServiceReference.IUS_MRD_MeterReadingRequestType RequestTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustAccountNum {
            get {
                return this.CustAccountNumField;
            }
            set {
                if ((object.ReferenceEquals(this.CustAccountNumField, value) != true)) {
                    this.CustAccountNumField = value;
                    this.RaisePropertyChanged("CustAccountNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MPODeliveryType {
            get {
                return this.MPODeliveryTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MPODeliveryTypeField, value) != true)) {
                    this.MPODeliveryTypeField = value;
                    this.RaisePropertyChanged("MPODeliveryType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MPOEANCode {
            get {
                return this.MPOEANCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MPOEANCodeField, value) != true)) {
                    this.MPOEANCodeField = value;
                    this.RaisePropertyChanged("MPOEANCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MPOMeteringPointId {
            get {
                return this.MPOMeteringPointIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MPOMeteringPointIdField, value) != true)) {
                    this.MPOMeteringPointIdField = value;
                    this.RaisePropertyChanged("MPOMeteringPointId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyAIFService.MyServicePortServiceReference.MeterDataInformation[] MeterDataInformationList {
            get {
                return this.MeterDataInformationListField;
            }
            set {
                if ((object.ReferenceEquals(this.MeterDataInformationListField, value) != true)) {
                    this.MeterDataInformationListField = value;
                    this.RaisePropertyChanged("MeterDataInformationList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyAIFService.MyServicePortServiceReference.EntityPostalAddress PostalAddress {
            get {
                return this.PostalAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalAddressField, value) != true)) {
                    this.PostalAddressField = value;
                    this.RaisePropertyChanged("PostalAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyAIFService.MyServicePortServiceReference.MeterRequests Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyAIFService.MyServicePortServiceReference.IUS_MRD_MeterReadingRequestType RequestType {
            get {
                return this.RequestTypeField;
            }
            set {
                if ((this.RequestTypeField.Equals(value) != true)) {
                    this.RequestTypeField = value;
                    this.RaisePropertyChanged("RequestType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeterRequests", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    [System.SerializableAttribute()]
    public partial class MeterRequests : MyAIFService.MyServicePortServiceReference.ITP_DataContract {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateReceivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateRequestCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RecIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ReceiverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RequestGenerationLogRefRecIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RequestedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyAIFService.MyServicePortServiceReference.IUS_MRD_Status StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Channel {
            get {
                return this.ChannelField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelField, value) != true)) {
                    this.ChannelField = value;
                    this.RaisePropertyChanged("Channel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateReceived {
            get {
                return this.DateReceivedField;
            }
            set {
                if ((this.DateReceivedField.Equals(value) != true)) {
                    this.DateReceivedField = value;
                    this.RaisePropertyChanged("DateReceived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateRequest {
            get {
                return this.DateRequestField;
            }
            set {
                if ((this.DateRequestField.Equals(value) != true)) {
                    this.DateRequestField = value;
                    this.RaisePropertyChanged("DateRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateRequestCreated {
            get {
                return this.DateRequestCreatedField;
            }
            set {
                if ((this.DateRequestCreatedField.Equals(value) != true)) {
                    this.DateRequestCreatedField = value;
                    this.RaisePropertyChanged("DateRequestCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryPoint {
            get {
                return this.DeliveryPointField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryPointField, value) != true)) {
                    this.DeliveryPointField = value;
                    this.RaisePropertyChanged("DeliveryPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Group {
            get {
                return this.GroupField;
            }
            set {
                if ((this.GroupField.Equals(value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RecId {
            get {
                return this.RecIdField;
            }
            set {
                if ((this.RecIdField.Equals(value) != true)) {
                    this.RecIdField = value;
                    this.RaisePropertyChanged("RecId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Receiver {
            get {
                return this.ReceiverField;
            }
            set {
                if ((this.ReceiverField.Equals(value) != true)) {
                    this.ReceiverField = value;
                    this.RaisePropertyChanged("Receiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RequestGenerationLogRefRecId {
            get {
                return this.RequestGenerationLogRefRecIdField;
            }
            set {
                if ((this.RequestGenerationLogRefRecIdField.Equals(value) != true)) {
                    this.RequestGenerationLogRefRecIdField = value;
                    this.RaisePropertyChanged("RequestGenerationLogRefRecId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdField, value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RequestedDateTime {
            get {
                return this.RequestedDateTimeField;
            }
            set {
                if ((this.RequestedDateTimeField.Equals(value) != true)) {
                    this.RequestedDateTimeField = value;
                    this.RaisePropertyChanged("RequestedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyAIFService.MyServicePortServiceReference.IUS_MRD_Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FindRequestArgs", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    [System.SerializableAttribute()]
    public partial class FindRequestArgs : MyAIFService.MyServicePortServiceReference.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdField, value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NoYes", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    public enum NoYes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yes = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IUS_MPO_MeterTimeFrames", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum IUS_MPO_MeterTimeFrames : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTF_B36_Exclusive_Night = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTF_B37_Total_Hours = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTF_B48_Not_Used = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTF_E10_Low = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTF_E11_High = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTF_E12_Peak = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTF_U00_Default_Time_To_Use = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTF_NPH_None_Peak_High = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTF_NPK_Non_Peak = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTF_NPL_Non_Peak_Low = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTF_PKH_Peak_High = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTF_PKL_Peak_Low = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTF_AMR_Defined = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTF_Mm3 = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTF_T10_Low_Injection = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTF_T11_High_Injection = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTF_Cogeneration = 17,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IUS_MRD_MeterReadingRequestType", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum IUS_MRD_MeterReadingRequestType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Event = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NonEvent = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SCC = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StatementCreation = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AgreementTermination = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PeriodicReading = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PredefinedReadingDate = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IUS_MRD_Status", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    public enum IUS_MRD_Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Requested = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Received = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rescheduled = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Estimated = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class AifFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomDetailXmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyAIFService.MyServicePortServiceReference.FaultMessageList[] FaultMessageListArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyAIFService.MyServicePortServiceReference.InfologMessage[] InfologMessageListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XppExceptionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml {
            get {
                return this.CustomDetailXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomDetailXmlField, value) != true)) {
                    this.CustomDetailXmlField = value;
                    this.RaisePropertyChanged("CustomDetailXml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyAIFService.MyServicePortServiceReference.FaultMessageList[] FaultMessageListArray {
            get {
                return this.FaultMessageListArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageListArrayField, value) != true)) {
                    this.FaultMessageListArrayField = value;
                    this.RaisePropertyChanged("FaultMessageListArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyAIFService.MyServicePortServiceReference.InfologMessage[] InfologMessageList {
            get {
                return this.InfologMessageListField;
            }
            set {
                if ((object.ReferenceEquals(this.InfologMessageListField, value) != true)) {
                    this.InfologMessageListField = value;
                    this.RaisePropertyChanged("InfologMessageList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType {
            get {
                return this.XppExceptionTypeField;
            }
            set {
                if ((this.XppExceptionTypeField.Equals(value) != true)) {
                    this.XppExceptionTypeField = value;
                    this.RaisePropertyChanged("XppExceptionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class FaultMessageList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyAIFService.MyServicePortServiceReference.FaultMessage[] FaultMessageArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOperationParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlPositionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation {
            get {
                return this.DocumentOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentOperationField, value) != true)) {
                    this.DocumentOperationField = value;
                    this.RaisePropertyChanged("DocumentOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyAIFService.MyServicePortServiceReference.FaultMessage[] FaultMessageArray {
            get {
                return this.FaultMessageArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageArrayField, value) != true)) {
                    this.FaultMessageArrayField = value;
                    this.RaisePropertyChanged("FaultMessageArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service {
            get {
                return this.ServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceField, value) != true)) {
                    this.ServiceField = value;
                    this.RaisePropertyChanged("Service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation {
            get {
                return this.ServiceOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationField, value) != true)) {
                    this.ServiceOperationField = value;
                    this.RaisePropertyChanged("ServiceOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter {
            get {
                return this.ServiceOperationParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationParameterField, value) != true)) {
                    this.ServiceOperationParameterField = value;
                    this.RaisePropertyChanged("ServiceOperationParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath {
            get {
                return this.XPathField;
            }
            set {
                if ((object.ReferenceEquals(this.XPathField, value) != true)) {
                    this.XPathField = value;
                    this.RaisePropertyChanged("XPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine {
            get {
                return this.XmlLineField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlLineField, value) != true)) {
                    this.XmlLineField = value;
                    this.RaisePropertyChanged("XmlLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition {
            get {
                return this.XmlPositionField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlPositionField, value) != true)) {
                    this.XmlPositionField = value;
                    this.RaisePropertyChanged("XmlPosition");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    [System.SerializableAttribute()]
    public partial class InfologMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MyAIFService.MyServicePortServiceReference.InfologMessageType InfologMessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyAIFService.MyServicePortServiceReference.InfologMessageType InfologMessageType {
            get {
                return this.InfologMessageTypeField;
            }
            set {
                if ((this.InfologMessageTypeField.Equals(value) != true)) {
                    this.InfologMessageTypeField = value;
                    this.RaisePropertyChanged("InfologMessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class FaultMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mynamespace", ConfigurationName="MyServicePortServiceReference.MyService")]
    public interface MyService {
        
        // CODEGEN: Generating message contract since the wrapper name (MyServiceFindRequestRequest) of message MyServiceFindRequestRequest does not match the default value (FindRequest)
        [System.ServiceModel.OperationContractAttribute(Action="http://mynamespace/MyService/FindRequest", ReplyAction="http://mynamespace/MyService/FindRequestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MyAIFService.MyServicePortServiceReference.AifFault), Action="http://mynamespace/MyService/FindRequestAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        MyAIFService.MyServicePortServiceReference.MyServiceFindRequestResponse FindRequest(MyAIFService.MyServicePortServiceReference.MyServiceFindRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mynamespace/MyService/FindRequest", ReplyAction="http://mynamespace/MyService/FindRequestResponse")]
        System.Threading.Tasks.Task<MyAIFService.MyServicePortServiceReference.MyServiceFindRequestResponse> FindRequestAsync(MyAIFService.MyServicePortServiceReference.MyServiceFindRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MyServiceFindRequestRequest", WrapperNamespace="http://mynamespace", IsWrapped=true)]
    public partial class MyServiceFindRequestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public MyAIFService.MyServicePortServiceReference.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mynamespace", Order=0)]
        public MyAIFService.MyServicePortServiceReference.FindRequestArgs _args;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mynamespace", Order=1)]
        public string _languageID;
        
        public MyServiceFindRequestRequest() {
        }
        
        public MyServiceFindRequestRequest(MyAIFService.MyServicePortServiceReference.CallContext CallContext, MyAIFService.MyServicePortServiceReference.FindRequestArgs _args, string _languageID) {
            this.CallContext = CallContext;
            this._args = _args;
            this._languageID = _languageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MyServiceFindRequestResponse", WrapperNamespace="http://mynamespace", IsWrapped=true)]
    public partial class MyServiceFindRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mynamespace", Order=0)]
        public MyAIFService.MyServicePortServiceReference.MeterReadingRequest[] response;
        
        public MyServiceFindRequestResponse() {
        }
        
        public MyServiceFindRequestResponse(MyAIFService.MyServicePortServiceReference.MeterReadingRequest[] response) {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyServiceChannel : MyAIFService.MyServicePortServiceReference.MyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceClient : System.ServiceModel.ClientBase<MyAIFService.MyServicePortServiceReference.MyService>, MyAIFService.MyServicePortServiceReference.MyService {
        
        public MyServiceClient() {
        }
        
        public MyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyAIFService.MyServicePortServiceReference.MyServiceFindRequestResponse MyAIFService.MyServicePortServiceReference.MyService.FindRequest(MyAIFService.MyServicePortServiceReference.MyServiceFindRequestRequest request) {
            return base.Channel.FindRequest(request);
        }
        
        public MyAIFService.MyServicePortServiceReference.MeterReadingRequest[] FindRequest(MyAIFService.MyServicePortServiceReference.CallContext CallContext, MyAIFService.MyServicePortServiceReference.FindRequestArgs _args, string _languageID) {
            MyAIFService.MyServicePortServiceReference.MyServiceFindRequestRequest inValue = new MyAIFService.MyServicePortServiceReference.MyServiceFindRequestRequest();
            inValue.CallContext = CallContext;
            inValue._args = _args;
            inValue._languageID = _languageID;
            MyAIFService.MyServicePortServiceReference.MyServiceFindRequestResponse retVal = ((MyAIFService.MyServicePortServiceReference.MyService)(this)).FindRequest(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyAIFService.MyServicePortServiceReference.MyServiceFindRequestResponse> MyAIFService.MyServicePortServiceReference.MyService.FindRequestAsync(MyAIFService.MyServicePortServiceReference.MyServiceFindRequestRequest request) {
            return base.Channel.FindRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyAIFService.MyServicePortServiceReference.MyServiceFindRequestResponse> FindRequestAsync(MyAIFService.MyServicePortServiceReference.CallContext CallContext, MyAIFService.MyServicePortServiceReference.FindRequestArgs _args, string _languageID) {
            MyAIFService.MyServicePortServiceReference.MyServiceFindRequestRequest inValue = new MyAIFService.MyServicePortServiceReference.MyServiceFindRequestRequest();
            inValue.CallContext = CallContext;
            inValue._args = _args;
            inValue._languageID = _languageID;
            return ((MyAIFService.MyServicePortServiceReference.MyService)(this)).FindRequestAsync(inValue);
        }
    }
}
